In [2]:
import numpy as np
import pandas as pd
from bs4 import BeautifulSoup
from urllib.request import urlopen

In [3]:
from tqdm import tqdm_notebook
from selenium import webdriver
import time

In [4]:
driver = webdriver.Chrome('driver/chromedriver')
driver.get("http://franchise.ftc.go.kr/user/extra/main/70/firHope/listBrand/jsp/LayOutPage.do")

In [5]:
year_list_raw = driver.find_element_by_xpath("""//*[@id="selYear"]""")
year_list = year_list_raw.find_elements_by_tag_name("option")
year_names_values = [option.text for option in year_list]
year_names_values = year_names_values[:]
year_names_values

['2017', '2016', '2015']

In [6]:
indus_list_raw = driver.find_element_by_xpath("""//*[@id="selIndus"]""")
indus_list = indus_list_raw.find_elements_by_tag_name("option")
indus_names_values = [option.text for option in indus_list]
indus_names_values = indus_names_values[1:]
indus_names_values

['한식',
 '분식',
 '중식',
 '일식',
 '서양식',
 '기타 외국식',
 '패스트푸드',
 '치킨',
 '피자',
 '제과제빵',
 '아이스크림/빙수 ',
 '커피',
 '음료 (커피 외)',
 '주점',
 '기타 외식']

In [7]:
report_list_raw = driver.find_element_by_xpath("""//*[@id="selListType"]""")
report_list = report_list_raw.find_elements_by_tag_name("option")
report_names_values = [option.text for option in report_list]
report_names_values = report_names_values[:]
report_names_values

['브랜드 개요', '가맹점 현황 정보', '가맹점 창업비용']

In [ ]:
r = []

year = driver.find_element_by_id("selYear") #년도
year.send_keys(year_names_values[0])
    
for j in range(0,len(indus_names_values)):
    indus = driver.find_element_by_id("selIndus") #업종 중분류
    indus.send_keys(indus_names_values[j])
        
    for k in range(0,len(report_names_values)):
        report = driver.find_element_by_id("selListType") #비교항목
        report.send_keys(report_names_values[k])
        driver.find_element_by_xpath("""//*[@id="frmSearch"]/input[5]""").click()
            
        html=driver.page_source
        soup=BeautifulSoup(html,'html.parser')
            
        len(soup.find_all('td'))/6
            
        print(report_names_values[k])####

        rows = []        
        for row in range(int(len(soup.find_all('td'))/6)):
            row1 = []

            for i in range(0+(row*6), 6+(row*6)) :
                tmp = soup.find_all('td')[i].get_text()
                tmp = tmp.replace('\n','')
                tmp = tmp.replace('\t','')
                tmp = tmp.replace('\xa0','')

                row1.append(tmp)
            rows.append(row1)
        r.append(rows)
    print(indus_names_values[j], 'done!')

In [10]:
r = []
length = [6,9,10]
for k in range(0,len(report_names_values)):  
    year = driver.find_element_by_id("selYear") #년도
    year.send_keys(year_names_values[0])
    indus = driver.find_element_by_id("selIndus") #업종 중분류
    indus.send_keys(indus_names_values[0])
    report = driver.find_element_by_id("selListType") #비교항목
    report.send_keys(report_names_values[k])
    driver.find_element_by_xpath("""//*[@id="frmSearch"]/input[5]""").click()
            
    html=driver.page_source
    soup=BeautifulSoup(html,'html.parser')
    
    print(report_names_values[k])####
    
    rows = []        
    for row in range(int(len(soup.find_all('td'))/length[k])):
        row1 = []

        for i in range(0+(row*length[k]), length[k]+(row*length[k])) :
            tmp = soup.find_all('td')[i].get_text()
            tmp = tmp.replace('\n','')
            tmp = tmp.replace('\t','')
            tmp = tmp.replace('\xa0','')

            row1.append(tmp)
        rows.append(row1)
    r.append(rows)
print('done!')

브랜드 개요
가맹점 현황 정보
가맹점 창업비용
done!

In [12]:
pd.DataFrame(r[2])

,0,1,2,3,4,5,6,7,8,9
0,평균,-,"8,770","3,798","3,468","94,790","110,828(1.00)","1,650",117,"55,203"
1,누들박스,(주)누들박스,"19,800","16,500","20,000","1,143,500","1,199,800(10.83)","2,750",66,"55,000"
2,포항물회,햇살바다(주),"5,500","2,200","3,000","760,300","771,000(6.96)","1,650",66,"33,000"
3,G글G글오돌구이,(주)나눔에프씨,"11,000","5,500","3,000","731,150","750,650(6.77)","1,760",66,"35,200"
4,하누소,(주)하누소푸드시스템,"33,000","1,100","20,000","681,670","735,770(6.64)","2,420",495,"363,000"
5,무한한판8.8,(주)조은세상에프앤씨,"11,000","3,300","3,000","634,500","651,800(5.88)","16,500",99,"495,000"
6,프리-엠베네치아(PRE-m 베네치아),에프앤에프베네치아,"17,500","5,500","5,000","580,000","608,000(5.49)","2,420",495,"363,000"
7,풀잎채,(주)풀잎채,"55,000",0,"10,000","523,689","588,689(5.31)","2,552",379.5,"293,480"
8,날마다대박나는집,(주)명진푸드,"5,500","3,300",0,"541,200","550,000(4.96)","2,200",495,"330,000"
9,다담골,에프앤에프베네치아,"17,500","5,500","5,000","494,000","522,000(4.71)","2,420",495,"363,000"
10,토끼정,(주)토끼정,"33,000","22,000",0,"421,300","476,300(4.30)","3,135",264,"250,800"
11,백년갈비,예스람,"22,000","11,000","5,000","407,000","445,000(4.02)","3,300",330,"330,000"
12,불끈낙지,예스람,"22,000","11,000","5,000","407,000","445,000(4.02)","3,300",330,"330,000"
13,꽃마름,(주)예울에프씨,"16,500","11,000","2,000","395,000","424,500(3.83)","1,300",495,"195,000"
14,다담뜰 한식뷔페,(주)다담뜰,"27,500","38,500","10,000","348,150","424,150(3.83)","1,595",429,"207,350"
15,엔테이블(nTable),(주)놀부,"10,450","5,500","10,000","397,100","423,050(3.82)","1,936",330,"193,600"
16,참한상 쭈꾸미,(주)참한세상,"11,000","5,500","3,000","390,500","410,000(3.70)","1,650",198,"99,000"
17,심민속촌,에코푸드(주),"24,200","11,000","20,000","339,900","395,100(3.56)","1,687",495,"253,000"
18,일편등심,에스에이치푸드,"5,500","2,200","5,000","376,200","388,900(3.51)","1,760",396,"211,200"
19,나정상회,나정상회,"16,500","5,500","30,000","319,000","371,000(3.35)","2,200",330,"220,000"
20,육칠팔,(주)육칠팔,"22,000","2,200","5,000","341,704","370,904(3.35)","2,090",330,"209,000"
21,채선당,(주)채선당,"11,000","11,000","10,000","338,439","370,439(3.34)","1,870",330,"187,000"
22,샤브홀리,샤브홀리,"16,500","5,500",0,"339,000","361,000(3.26)","1,980",330,"198,000"
23,가인채샤브샤브&샐러드,(주)가인채,"22,000","5,500","3,000","327,500","358,000(3.23)","2,000",330,"200,000"
24,착한전복,(주)두둑한행복,"11,000","11,000",0,"329,500","351,500(3.17)","1,650",330,"165,000"
25,숟가락반상 마실,마실,"22,000","11,000","5,000","310,937","348,937(3.15)","1,870",330,"187,000"
26,반주(BANJOO),(주)캘리스코,"23,100","3,300","35,000","281,000","342,400(3.09)","5,000",132,"200,000"
27,신선설농탕,(주)쿠드,"55,000",0,"50,000","237,380","342,380(3.09)","3,300",99,"99,000"
28,미소육화,(주)지케이푸드,"11,000","3,300","5,000","307,410","326,710(2.95)","1,540",330,"154,000"
29,본가,(주)더본코리아,"36,960",0,"12,000","276,411","325,371(2.94)","1,705",330,"170,500"
...,...,...,...,...,...,...,...,...,...,...
1198,장충미도왕족발보쌈,(주)미도식품,"3,300",0,"1,000","16,000","20,300(0.18)","3,333",9.9,"10,000"
1199,대사관,청계식품,"1,100",0,500,"18,300","19,900(0.18)","1,340",33,"13,400"
1200,쌀눈쌀 현미누룽지,(주)엄마,"3,300",550,"1,000","14,850","19,700(0.18)",770,16.5,"3,850"
1201,춘부집목살스테끼와껍데기,(주)더푸드상상,"5,500","2,200","3,000","7,920","18,620(0.17)",132,99,"3,960"
1202,인사동직화,(주)미당에프앤비,"11,000",0,"2,000","5,555","18,555(0.17)",165,66,"3,300"
1203,육미명가옛날아우내순대&보쌈,(주)병천아우내식품,"5,500","3,300","3,000","5,700","17,500(0.16)",0,0,0
1204,병천황토방순대,(주)병천아우내식품,"5,500","3,300","3,000","5,700","17,500(0.16)",0,0,0
1205,할매닭발,(유)서빈글로벌,0,0,"2,000","15,000","17,000(0.15)","1,100",33,"11,000"
1206,쉐프삼촌,쉐프삼촌,"13,200","3,300",0,0,"16,500(0.15)","1,870",66,"37,400"
1207,왔쏘,(주)다드림에프앤비,"13,200","3,300",0,0,"16,500(0.15)",0,0,0
1208,인생극장,(주)에이치티코리아,"5,500","5,500","1,000","4,400","16,400(0.15)",0,0,0
1209,바보돼지두마리,돼지두마리 장전점,"5,500","3,300","2,000","4,780","15,580(0.14)","1,650",39.6,"19,800"
1210,족쌈베이크,(주)토담,0,"3,300",0,"12,100","15,400(0.14)",550,33,"5,500"
1211,남천닭갈비,(주)라온에프에스,"6,000","1,000",0,"8,200","15,200(0.14)",120,33,"1,200"
1212,평창동태찌개찜,평창동태찌개찜,"3,300","2,200",0,"9,500","15,000(0.14)",0,99,0
1213,흙에서,정인,"11,000","3,300",300,0,"14,600(0.13)","1,650",33,"16,500"
1214,양평서울해장국 큰아들집,(주)정금F&C,"5,500","3,300","5,000",0,"13,800(0.12)","1,430",99,"42,900"
1215,돈꾸락,돈꾸락,"2,750","2,200","1,000","7,150","13,100(0.12)",0,33,0
1216,약초마을,약초마을 YCM,"11,000",0,"2,000",0,"13,000(0.12)",0,0,0
1217,보고싶다,(주)에스에이치,"5,500","5,500","2,000",0,"13,000(0.12)","1,650",82.5,"41,250"
1218,옛밥사랑,(주)늘솜푸드,"2,200","1,100","1,000","8,560","12,860(0.12)",0,0,0
1219,미스몽도시락,(주)푸드몽,"5,500","2,200","1,000","4,070","12,770(0.12)","1,650",33,"16,500"
1220,바른생갈비,(주)바른푸드,"5,500","3,300","3,000",0,"11,800(0.11)",990,66,"19,800"
1221,양평뚝배기해장국,(주)뉴서진식품,"5,500","2,200","1,000","2,200","10,900(0.10)",0,0,0
1222,불티매운족발,(주)한아름푸드,"4,400","1,100",0,"5,390","10,890(0.10)","1,430",26.4,"11,440"
1223,쉐프돼지,쉐프돼지,"5,500","2,200","3,000",0,"10,700(0.10)","1,650",33,"16,500"
1224,돈푸대,햇빛과 바람,"2,750",0,0,"7,500","10,250(0.09)",175,66,"3,500"
1225,송가네왕족발,송가네식품(주),"3,300","2,200","3,000",0,"8,500(0.08)",0,0,0
1226,통뼈감자탕,(주)명가,"3,300",0,"2,000",0,"5,300(0.05)",0,0,0
1227,바다양푼이 동태탕 찜,(주)예진희알이에프,"3,800",0,0,0,"3,800(0.03)",0,0,0

In [ ]:
html=driver.page_source
soup=BeautifulSoup(html,'html.parser')

In [ ]:
len(soup.find_all('td'))/6

In [35]:
rows = []
for row in range(int(len(soup.find_all('td'))/6)):
    row1 = []
    
    for i in range(0+(row*6), 6+(row*6)) :
        tmp = soup.find_all('td')[i].get_text()
        tmp = tmp.replace('\n','')
        tmp = tmp.replace('\t','')
        tmp = tmp.replace('\xa0','')

        row1.append(tmp)
    rows.append(row1)

In [ ]:
data_frame = pd.DataFrame(r)
data_frame.to_csv('가나다.csv',encoding='utf-8')

In [ ]:
pd.DataFrame(r)

In [24]:
html=driver.page_source
soup=BeautifulSoup(html,'html.parser')

In [25]:
len(soup.find_all('td'))/6

326.0

In [26]:
rows = []
for row in range(int(len(soup.find_all('td'))/6)):
    
    row1 = []
    
    for i in range(0+(row*6), 6+(row*6)) :
        tmp = soup.find_all('td')[i].get_text()
        tmp = tmp.replace('\n','')
        tmp = tmp.replace('\t','')
        tmp = tmp.replace('\xa0','')

        row1.append(tmp)
    rows.extend(row1)

['평균',
 '-',
 '-',
 '4년11개월',
 '19.7',
 '47.3 명',
 '이삭토스트',
 '(주)이삭',
 '2003.08.02',
 '15년',
 '754',
 '42 명',
 '국수나무',
 '해피브릿지협동조합',
 '2006.08.11',
 '12년',
 '490',
 '101 명',
 '신전떡볶이',
 '신전푸드시스',
 '2009.01.02',
 '9년7개월',
 '452',
 '23 명',
 '김가네김밥',
 '(주)김가네',
 '1996.04.05',
 '22년4개월',
 '415',
 '78 명',
 '죠스떡볶이',
 '(주)죠스푸드',
 '2010.01.07',
 '8년7개월',
 '302',
 '26 명',
 '김밥천국',
 '(주)정다믄',
 '2001.12.26',
 '16년7개월',
 '282',
 '4 명',
 '바푸리',
 '(주)비피알',
 '2013.05.27',
 '5년2개월',
 '191',
 '48 명',
 '용우동',
 '(주)용마을',
 '1999.06.01',
 '19년2개월',
 '166',
 '15 명',
 '올떡볶이',
 '(주)지엔에스올떡',
 '2007.01.10',
 '11년7개월',
 '163',
 '12 명',
 '신포우리만두',
 '(유)신포우리식품',
 '1985.05.01',
 '33년3개월',
 '115',
 '89 명',
 '명인만두',
 '(주)명인에프엔비',
 '2003.10.29',
 '14년9개월',
 '112',
 '61 명',
 '신참떡볶이',
 '(주)신참에프앤씨',
 '2005.06.01',
 '13년2개월',
 '110',
 '2 명',
 '뚱스밥버거',
 '(주)일가인터내셔널',
 '2013.06.01',
 '5년2개월',
 '110',
 '23 명',
 '생생돈까스',
 '(주)에버리치에프앤비',
 '2005.06.01',
 '13년2개월',
 '103',
 '21 명',
 '빨봉분식',
 '(주)비엔피푸드',
 '2011.03.14',
 '7년5개월',
 '103',
 '14 명',
 '버무리떡볶이',
 '(주)이플푸드',
 '2008.05.03',
 '10년3개월',
 '98',
 '21 명',
 '토마토김밥',
 '(주)푸름에프앤에스',
 '2010.08.01',
 '8년',
 '95',
 '31 명',
 '토스트굽는사람들',
 '(주)케이비티',
 '2004.03.11',
 '14년5개월',
 '93',
 '7 명',
 '두끼',
 '(주)다른',
 '2015.03.24',
 '3년5개월',
 '88',
 '27 명',
 '국대떡볶이',
 '(주)국대에프앤비',
 '2009.11.30',
 '8년8개월',
 '84',
 '15 명',
 '종로김밥',
 '(주)제이알에프앤로지스',
 '2006.10.10',
 '11년10개월',
 '81',
 '10 명',
 '불스떡볶이',
 '(주) 비케이홀딩스',
 '2014.11.01',
 '3년9개월',
 '80',
 '11 명',
 '씨앤푸드스토리 청년떡볶이',
 '(주)씨앤푸드스토리',
 '2013.01.03',
 '5년7개월',
 '74',
 '2 명',
 '스쿨푸드',
 '(주)에스에프이노베이션',
 '2009.04.30',
 '9년3개월',
 '73',
 '332 명',
 '얌샘',
 '(주)얌샘',
 '2006.09.01',
 '11년11개월',
 '70',
 '38 명',
 '지지고(GGGO)',
 '(주)와이낫',
 '2011.09.10',
 '6년11개월',
 '69',
 '12 명',
 '황기순의칼국수앤왕돈까스',
 '(주)티에스에프엔씨',
 '2012.03.30',
 '6년4개월',
 '68',
 '21 명',
 '역전우동0410',
 '(주)더본코리아',
 '2012.04.30',
 '6년3개월',
 '67',
 '173 명',
 '명동할머니국수',
 '(주)봉원에프앤비',
 '2012.05.24',
 '6년3개월',
 '63',
 '26 명',
 '이웃집소녀떡볶이',
 '이웃집소녀쉐프',
 '2013.09.01',
 '4년11개월',
 '62',
 '2 명',
 '신불떡볶이',
 '신불식품',
 '2014.03.05',
 '4년5개월',
 '59',
 '1 명',
 '김밥나라',
 '(주)엠지에프앤씨',
 '2003.12.24',
 '14년8개월',
 '59',
 '3 명',
 '수유리우동집',
 '(주)물과소금',
 '2014.01.10',
 '4년7개월',
 '58',
 '5 명',
 '김밥천국',
 '나누리프랜차이즈',
 '2007.05.30',
 '11년2개월',
 '52',
 '1 명',
 '만복국수집',
 '(주)은혜푸드',
 '2007.09.15',
 '10년11개월',
 '52',
 '6 명',
 '킹콩떡볶이',
 '이심전심(주)',
 '2013.06.17',
 '5년2개월',
 '50',
 '10 명',
 '틈새라면',
 '(주)틈새상사',
 '2002.11.28',
 '15년8개월',
 '50',
 '3 명',
 '신떡',
 '(주)신화에프앤비',
 '2001.10.16',
 '16년10개월',
 '50',
 '2 명',
 '김밥킹',
 '(주)아이윈엔터프라이즈',
 '2015.03.04',
 '3년5개월',
 '44',
 '16 명',
 '북문로떡볶이',
 '(주)북문로키친',
 '2013.11.11',
 '4년9개월',
 '43',
 '14 명',
 '공수간',
 '(주)놀부',
 '2012.09.12',
 '5년11개월',
 '43',
 '311 명',
 '씨앗호떡',
 '(주)에스엔인더스트리',
 '2013.05.01',
 '5년3개월',
 '42',
 '11 명',
 '걸작떡볶이',
 '(주)위드인푸드',
 '2014.03.11',
 '4년5개월',
 '42',
 '14 명',
 '꾼떡',
 '(주)트로이',
 '2008.08.17',
 '10년',
 '41',
 '6 명',
 '로봇김밥',
 '(주)로봇에프앤비',
 '2014.03.01',
 '4년5개월',
 '38',
 '15 명',
 '밥맛나는세상',
 '(주)소디프비앤에프',
 '2015.04.30',
 '3년3개월',
 '37',
 '189 명',
 '아리가또맘마',
 '(주)트렌차이즈',
 '2011.03.28',
 '7년4개월',
 '37',
 '14 명',
 '나드리김밥',
 '(주)나드리에프에스',
 '2013.10.01',
 '4년10개월',
 '35',
 '5 명',
 '깨순이김밥',
 '(유)대성물류',
 '2004.01.28',
 '14년6개월',
 '31',
 '6 명',
 '송촌꼬마김밥',
 '송촌꼬마김밥',
 '2015.10.15',
 '2년10개월',
 '31',
 '3 명',
 '요런떡볶이',
 '(주)자연애몸',
 '2009.02.12',
 '9년6개월',
 '31',
 '6 명',
 '디델리',
 '(주)디엔에프씨',
 '2004.10.15',
 '13년10개월',
 '30',
 '2 명',
 '웁스떡볶이',
 '웁스에프앤씨',
 '2013.04.01',
 '5년4개월',
 '29',
 '2 명',
 '찰스숯불김밥',
 '(주)찰스푸드',
 '2013.02.21',
 '5년6개월',
 '29',
 '15 명',
 '울타리없는만두집',
 '제이앤푸드',
 '2015.03.13',
 '3년5개월',
 '29',
 '0 명',
 '빨간망토',
 '(주)일가인터내셔널',
 '2015.09.01',
 '2년11개월',
 '29',
 '23 명',
 '나는 조선의 떡볶이다',
 '이노레시피',
 '2014.12.22',
 '3년8개월',
 '29',
 '2 명',
 '밀크밥버거',
 '(주)오색만찬',
 '2013.04.01',
 '5년4개월',
 '28',
 '62 명',
 '소문난공주떡볶이',
 '아이제이(IJ)푸드',
 '2009.11.14',
 '8년9개월',
 '28',
 '1 명',
 '새벽길빨간오뎅',
 '설화식품',
 '2003.08.16',
 '15년',
 '26',
 '5 명',
 '델리웨건와작',
 '(주)모음',
 '2012.01.07',
 '6년7개월',
 '26',
 '149 명',
 '신만용 신가네매운떡볶이',
 '신만용 신가네매운떡볶이',
 '2014.03.14',
 '4년5개월',
 '25',
 '1 명',
 '얌스',
 '(주)새모양에프앤비',
 '2009.12.17',
 '8년8개월',
 '25',
 '12 명',
 '서가원김밥',
 '(주)오색만찬',
 '2014.03.10',
 '4년5개월',
 '23',
 '62 명',
 '눈물떡볶이',
 '(주)눈물패밀리',
 '2016.08.01',
 '2년',
 '23',
 '9 명',
 '스쿨스토어',
 '(주)스쿨스토어',
 '2011.04.27',
 '7년3개월',
 '23',
 '12 명',
 '오정은A김밥',
 '(주)오정은',
 '2014.09.30',
 '3년10개월',
 '22',
 '13 명',
 '보용만두',
 '(주)보용에프앤씨',
 '2008.08.25',
 '10년',
 '22',
 '10 명',
 '라스타',
 '(주)마스타브렌드코리아',
 '2015.05.01',
 '3년3개월',
 '20',
 '11 명',
 '채다올김밥',
 '다올에프엔씨',
 '2014.01.01',
 '4년7개월',
 '20',
 '1 명',
 '몬나니떡볶이',
 '(주)몬스푸드',
 '2015.06.01',
 '3년2개월',
 '20',
 '6 명',
 '왕순이 주먹밥 김밥',
 '(주)왕순이',
 '2013.05.05',
 '5년3개월',
 '20',
 '5 명',
 '영심이떡볶이앤김밥',
 '(주)아름드리',
 '2013.04.15',
 '5년4개월',
 '20',
 '11 명',
 '삼청동궁물떡볶이',
 '(주)삼청동에프앤씨',
 '2014.04.30',
 '4년3개월',
 '19',
 '4 명',
 '내고향냉면만두',
 '고석환손만두',
 '2011.03.09',
 '7년5개월',
 '19',
 '4 명',
 '고수라',
 '고수라김밥 호남지사',
 '2016.11.17',
 '1년9개월',
 '19',
 '1 명',
 '초읍만두',
 '초읍만두',
 '2015.07.01',
 '3년1개월',
 '19',
 '5 명',
 '애플김밥',
 '(주)애플김밥',
 '2010.11.05',
 '7년9개월',
 '18',
 '7 명',
 '반장떡볶이',
 '(주)반장푸드',
 '2014.04.01',
 '4년4개월',
 '18',
 '7 명',
 '가마솥김밥',
 '(주)도시방앗간',
 '2014.06.20',
 '4년2개월',
 '18',
 '4 명',
 '더돈까스(the돈까스)',
 '에그트리',
 '2014.02.01',
 '4년6개월',
 '18',
 '3 명',
 '석관동 떡볶이',
 '오리엔트 푸드',
 '2015.09.05',
 '2년11개월',
 '18',
 '18 명',
 '바울아저씨',
 '(주)바울코리아',
 '2013.12.05',
 '4년8개월',
 '18',
 '4 명',
 '오떡',
 '(주)에이치앤비푸드',
 '2013.10.04',
 '4년10개월',
 '18',
 '2 명',
 '신천할매떡볶이',
 '신천할매떡볶이',
 '1998.02.01',
 '20년6개월',
 '17',
 '6 명',
 '신탕국물떡볶이',
 '신탕국물떡볶이',
 '2014.03.17',
 '4년5개월',
 '17',
 '0 명',
 '불볶이와튀김범벅',
 '칠사푸드',
 '2009.10.02',
 '8년10개월',
 '17',
 '1 명',
 '오별난멸치국수',
 '(주)누들앤푸드',
 '2015.06.29',
 '3년1개월',
 '17',
 '6 명',
 '성경만두요리전문점',
 '(주)성경에프앤에스',
 '2014.07.21',
 '4년1개월',
 '17',
 '5 명',
 '미정국수0410',
 '(주)더본코리아',
 '2009.09.24',
 '8년11개월',
 '17',
 '173 명',
 '으니의수라간',
 '(주)원스에프엔비',
 '2013.01.14',
 '5년7개월',
 '17',
 '7 명',
 '응급실국물떡볶이',
 '(주)금해코리아',
 '2014.12.13',
 '3년8개월',
 '17',
 '7 명',
 '김피라(kimpira)',
 '(주)솔트앤슈가',
 '2015.06.11',
 '3년2개월',
 '17',
 '18 명',
 '심할머니안흥찐빵만두',
 '어우리',
 '2016.04.10',
 '2년4개월',
 '17',
 '1 명',
 '마리짱',
 '(주)삼봉',
 '2014.10.01',
 '3년10개월',
 '16',
 '9 명',
 '뽀뚜루까아저씨',
 '(주)뽀뚜루까에프엔비',
 '2001.05.01',
 '17년3개월',
 '16',
 '7 명',
 '목동수제돈가스',
 '서준식품',
 '2015.10.10',
 '2년10개월',
 '16',
 '1 명',
 '레드썬',
 '(주)제이케이푸드',
 '2010.08.01',
 '8년',
 '16',
 '3 명',
 '남천할매떡볶이',
 '(주)남천에프앤비',
 '2010.11.05',
 '7년9개월',
 '15',
 '19 명',
 '마포만두',
 '(주)다우림푸드',
 '2010.04.12',
 '8년4개월',
 '15',
 '16 명',
 '참숯불닭발불떡볶이',
 '(주)다윈에프앤피',
 '2014.06.13',
 '4년2개월',
 '15',
 '4 명',
 '사나이김밥',
 '(주)사나이',
 '2014.07.08',
 '4년1개월',
 '14',
 '2 명',
 '우럼마왕만두',
 '우럼마에프앤디',
 '2010.10.01',
 '7년10개월',
 '14',
 '1 명',
 '수김밥',
 '손수푸드',
 '2015.05.15',
 '3년3개월',
 '14',
 '7 명',
 '고릴라버거&컵밥',
 '고릴라버거',
 '2015.12.01',
 '2년8개월',
 '14',
 '1 명',
 '먹쉬돈나',
 '(주)빅바이트에프엔비',
 '2006.12.01',
 '11년8개월',
 '14',
 '10 명',
 '분식의신 분신',
 '(주)에스지푸드',
 '2015.01.14',
 '3년7개월',
 '13',
 '9 명',
 '소담비빔국수',
 '(주)태강에프앤씨',
 '2009.11.30',
 '8년8개월',
 '13',
 '6 명',
 '신화신가네매운떡볶이',
 '신화',
 '2010.12.10',
 '7년8개월',
 '13',
 '4 명',
 '호봉토스트위치',
 '(주)호봉푸드시스템',
 '2005.05.21',
 '13년3개월',
 '13',
 '4 명',
 '소문난왕만두찐빵',
 '소문난식품',
 '2007.03.10',
 '11년5개월',
 '13',
 '15 명',
 '불탕국물떡볶이',
 '불탕국물떡볶이',
 '2015.04.03',
 '3년4개월',
 '12',
 '1 명',
 '모범떡볶이 1976',
 '(주)우진케이티에스',
 '2014.11.25',
 '3년9개월',
 '12',
 '2 명',
 '우리동네면반장',
 '(주)우리동네에프앤비',
 '2013.11.01',
 '4년9개월',
 '12',
 '7 명',
 '홍연자명품김밥',
 '홍연자창업센터',
 '2010.10.26',
 '7년9개월',
 '12',
 '2 명',
 '정성한줄',
 '(주)해밀코리아',
 '2015.07.05',
 '3년1개월',
 '12',
 '4 명',
 '단오방',
 '(주)단오푸드',
 '2014.10.01',
 '3년10개월',
 '12',
 '3 명',
 '동떡 동대문매운떡볶이',
 '동대문떡볶이 동떡',
 '2014.07.15',
 '4년1개월',
 '11',
 '1 명',
 '고고즉석떡볶이',
 '(주)고고푸드',
 '2013.04.05',
 '5년4개월',
 '11',
 '2 명',
 '부송국수',
 '부송푸드',
 '2009.06.04',
 '9년2개월',
 '11',
 '4 명',
 '뿅떡',
 '본가경',
 '2012.12.10',
 '5년8개월',
 '11',
 '1 명',
 '더바스켓',
 '(주)성하식품',
 '2014.09.01',
 '3년11개월',
 '11',
 '3 명',
 '엄청난떡볶이',
 '엄청난떡볶이',
 '2014.04.01',
 '4년4개월',
 '11',
 '1 명',
 '삼화푸드몰',
 '삼화식품',
 '1997.05.01',
 '21년3개월',
 '11',
 '8 명',
 '보영만두',
 '(주)보영',
 '2008.01.30',
 '10년6개월',
 '10',
 '9 명',
 '오백국수',
 '오백제작소',
 '2015.10.01',
 '2년10개월',
 '10',
 '1 명',
 '셰프의돈까스',
 '이든푸드그룹',
 '2017.04.16',
 '1년4개월',
 '10',
 '0 명',
 '효형제돈까스',
 '효브라더스',
 '2015.05.25',
 '3년3개월',
 '10',
 '1 명',
 '병규돈가스',
 '(주)병규돈가스',
 '2012.02.26',
 '6년5개월',
 '10',
 '4 명',
 '크레이지떡',
 '(주)참에프앤디',
 '2008.10.02',
 '9년10개월',
 '10',
 '5 명',
 '차차',
 '(주)차차',
 '2016.02.10',
 '2년6개월',
 '10',
 '5 명',
 '원빙고떡볶이',
 '다보유통',
 '2013.02.18',
 '5년6개월',
 '10',
 '1 명',
 '하나돈까스',
 '(주)파나',
 '2008.06.01',
 '10년2개월',
 '9',
 '13 명',
 '홍쌤떡볶이',
 '홍성민쌤 떡볶이',
 '2014.10.01',
 '3년10개월',
 '9',
 '1 명',
 '떡볶이삼촌',
 '엉클푸드',
 '2012.01.01',
 '6년7개월',
 '9',
 '1 명',
 '달떡떡볶이파는사람들',
 '씨앤피푸드',
 '2015.05.11',
 '3년3개월',
 '9',
 '2 명',
 '아딸',
 '(주)아딸',
 '2015.10.20',
 '2년10개월',
 '8',
 '5 명',
 '바른면집',
 '(주)치즈명가',
 '2016.08.30',
 '1년11개월',
 '8',
 '8 명',
 '구윤희 따뜻한밥상 김밥일번지',
 '(주)금환식품',
 '2015.04.27',
 '3년3개월',
 '8',
 '21 명',
 '릴라밥집',
 '릴라식품',
 '2011.12.26',
 '6년7개월',
 '8',
 '4 명',
 '파더스김밥',
 '(주)미셰프',
 '2015.03.12',
 '3년5개월',
 '7',
 '2 명',
 '이여사나무김밥',
 '(주)다온코리아',
 '2013.09.25',
 '4년11개월',
 '7',
 '3 명',
 '맹구분식',
 '(주)상향평준화',
 '2015.12.09',
 '2년8개월',
 '7',
 '2 명',
 '삐사감김밥',
 '삐사감김밥',
 '2014.08.10',
 '4년',
 '7',
 '6 명',
 '신호탕떡볶이',
 '미호푸드',
 '2014.05.29',
 '4년2개월',
 '7',
 '1 명',
 '바로먹는 풀코스 ',
 '(주)바풀(BAPOOL)',
 '2013.07.24',
 '5년1개월',
 '7',
 '4 명',
 '분식제일가',
 '(주)쿡앤리빙',
 '2016.04.27',
 '2년3개월',
 '7',
 '13 명',
 '우리동네 국수집',
 '(주)봉화산푸드',
 '2015.06.01',
 '3년2개월',
 '7',
 '9 명',
 '추억의국민학교떡볶이',
 '(주)팔도에프씨',
 '2015.04.01',
 '3년4개월',
 '7',
 '5 명',
 '흥남부두',
 '브라더식품',
 '2015.04.30',
 '3년3개월',
 '7',
 '8 명',
 '리김밥',
 '(주)바인인터내셔날',
 '2015.05.25',
 '3년3개월',
 '7',
 '14 명',
 '다다믄충무김밥',
 '다다믄충무김밥',
 '2013.06.25',
 '5년2개월',
 '6',
 '1 명',
 '안양돈까스',
 '에버그린',
 '2016.08.03',
 '2년',
 '6',
 '2 명',
 '또뽀끼야',
 '또뽀끼야',
 '2011.11.16',
 '6년9개월',
 '6',
 '1 명',
 '엉클통김밥',
 '(주)통에프앤씨',
 '2013.04.01',
 '5년4개월',
 '6',
 '4 명',
 '승아의기묘한떡볶이',
 '기묘한F&B',
 '2016.05.30',
 '2년2개월',
 '6',
 '2 명',
 '여러분식',
 '(주)미도비앤케이',
 '2015.07.04',
 '3년1개월',
 '6',
 '3 명',
 '셰프의국수전',
 '(주)바인에프씨',
 '2011.03.08',
 '7년5개월',
 '6',
 '6 명',
 '인정국물떡볶이',
 '두레푸드',
 '2016.04.21',
 '2년4개월',
 '6',
 '1 명',
 'LA김밥',
 '(주)한국창업경제연구소',
 '2015.05.18',
 '3년3개월',
 '6',
 '11 명',
 '홍코너',
 '(주)더프랜즈에프앤비',
 '2014.12.02',
 '3년8개월',
 '6',
 '3 명',
 '임대표',
 '(주)대표컴퍼니',
 '2016.01.12',
 '2년7개월',
 '6',
 '1 명',
 '돈호야',
 '(주)퍼스트에이엔티',
 '2010.11.01',
 '7년9개월',
 '5',
 '34 명',
 '촌빨떡볶이',
 '촌빨떡볶이',
 '2014.03.07',
 '4년5개월',
 '5',
 '1 명',
 '땡벌딜리버리',
 '너랑나랑',
 '2015.11.23',
 '2년9개월',
 '5',
 '1 명',
 '불땡국수',
 '(주)착한푸드',
 '2016.03.23',
 '2년5개월',
 ...]

In [16]:
data_frame = pd.DataFrame(r)
data_frame.to_csv('가나다.csv',encoding='utf-8')

NameError: name 'r' is not defined

In [ ]:
pd.DataFrame(r)

In [ ]:
rows

In [ ]:
url = list1[0]
html = urlopen(url)
soup = BeautifulSoup(html,'html.parser')

In [ ]:
#가맹본부 일반 현황
row1=[]
for i in range(0,6) :
    tmp = soup.find_all('td')[i].get_text()
#     tmp1 = tmp.split('\r')[1]    
    tmp = tmp.replace('\n','')
    tmp = tmp.replace('\t','')
    tmp = tmp.replace('\xa0','')
    if tmp == '' :
        tmp = tmp.split('\r')[2]
        tmp = tmp.replace('\n','')
        tmp = tmp.replace('\t','')     
    row1.append(tmp)

In [ ]:
row1

In [ ]:
#주소, 사업자유형, 법인등록번호, 사업자등록번호
row2=[]
for i in range(12,16) :
    tmp = soup.find_all('td')[i].get_text()
    tmp1 = tmp.split('\r')[1]    
    tmp1 = tmp1.replace('\n','')
    tmp1 = tmp1.replace('\t','')
    tmp1 = tmp1.replace('\xa0','')
    if tmp1 == '' :
        tmp1 = tmp.split('\r')[2]
        tmp1 = tmp1.replace('\n','')
        tmp1 = tmp1.replace('\t','')
        tmp1 = tmp1.replace('\xa0','')
    row2.append(tmp1)

In [ ]:
#가맹본부 재무상황
row3=[]
for i in range(16,40) :
    tmp = soup.find_all('td')[i].get_text()
    if tmp == '' :
        row3.append(tmp)
        continue
    try :
        tmp1 = tmp.split('\r')[1]    
    except : 
        tmp1 = tmp
    tmp1 = tmp1.replace('\n','')
    tmp1 = tmp1.replace('\t','')
    if tmp1 == '' :
        tmp1 = tmp.split('\r')[2]
        tmp1 = tmp1.replace('\n','')
        tmp1 = tmp1.replace('\t','')    
    row3.append(tmp1)

In [ ]:
#가맹사업 임직원수, 가맹본부 브랜드 및 가맹사업 계열사 수, 가맹사업 개시일
row4=[]
for i in range(40,46) :
    tmp = soup.find_all('td')[i].get_text()
    if tmp == '' :
        row4.append(tmp)
        continue
    try :
        tmp1 = tmp.split('\r')[1]    
    except : 
        tmp1 = tmp
    tmp1 = tmp1.replace('\n','')
    tmp1 = tmp1.replace('\t','')
    if tmp1 == '' :
        tmp1 = tmp.split('\r')[2]
        tmp1 = tmp1.replace('\n','')
        tmp1 = tmp1.replace('\t','')    
    row4.append(tmp1)
row4

In [ ]:
#그외
row5=[]
for i in range(46,len(soup.find_all('td'))) :
    tmp = soup.find_all('td')[i].get_text()
    tmp = tmp.replace('\n','')
    tmp = tmp.replace('\t','')
    tmp = tmp.replace('\r','')
    tmp = tmp.replace('\xa0','')    
    row5.append(tmp)
row5